# Generated by Django 4.2 on 2023-04-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('published_status', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('comment_time_create', models.DateTimeField(auto_now_add=True)),
                ('comment_time_update', models.DateTimeField(auto_now=True)),
                ('comment_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
