# Generated by Django 4.2 on 2023-06-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['time_create', 'time_update', 'title'], 'verbose_name': 'Документация', 'verbose_name_plural': 'Документация'},
        ),
        migrations.AlterField(
            model_name='forum',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='comment_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='published_status',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последней правки'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['-title'], name='forum_forum_title_4ba229_idx'),
        ),
        migrations.AddField(
            model_name='forum',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forum.category'),
        ),
    ]
