# Используем официальный образ PostgreSQL
FROM postgres:latest

# Настраиваем переменные окружения для PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres

# Копируем схему и данные (если нужно) в образ
# COPY schema.sql /docker-entrypoint-initdb.d/
# COPY data.sql /docker-entrypoint-initdb.d/

# По умолчанию, PostgreSQL слушает на порту 5432. Если нужен другой порт, можно задать так:
# EXPOSE 5432

# Если есть необходимость, вы можете указать дополнительные команды
# CMD ["postgres"]
